baseURL = "http://holgerschurig.github.io/"
languageCode = "en-us"
title = "Holger Schurig's Computer Calisthenics & Orthodontia"
author = "Holger Schurig"
theme = "my"
paginate = 12
enableRobotsTXT = true
pluralizelisttitles = false
relativeurls = true
pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = ""

[indexes]
tag = "tags"
topic = "topics"

[params]
subtitle = ""


# Use homepage.md instead of a list of posts
homepage = false
keywords = ["Linux","Emacs","Amateurfunk","Elektronik"]
#favicon = true
#mainSections = ["post"]
dateFormat = "02.01.2006"

# Navigation
# [[menu.main]]
# name = "English"
# url = "/en"
# weight = 1

# [[menu.main]]
# name = "Deutsch"
# url = "/de"
# weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

# [[menu.main]]
# name = "Topics"
# url = "/topics"
# weight = 4

# [[menu.main]]
# name = "Impressum"
# url = "/impressum"
# weight = 5

# Social Menu
#[[params.social]]
#name = "Github"
#icon = "fab fa-github"
#url = "https://github.com/dataCobra/hugo-vitae"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

# [[params.social]]
# name = "RSS"
# icon = "fas fa-rss"
# url = "/index.xml"
