baseURL = "http://holgerschurig.github.io/"
languageCode = "en-us"
title = "Holger Schurig's Computer Calisthenics & Orthodontia"
author = "Holger Schurig"
theme = "vitae"
paginate = 12
enableRobotsTXT = true
pluralizelisttitles = false
relativeurls = true
#copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
tag = "tags"
topic = "topics"
#series = "series"

[params]
# Use homepage.md instead of a list of posts
homepage = false

# Add meta keywords in head part (Site Keywords or Tags of Page)
keywords = ["hugo","vitae","theme","static"]

# Add meta description in head part
#description = "TODO Description."

# Add pagetitle to homepage <title> tag
#pagetitle = "TODO pagetitle"

# Add a subtitle to your website
subtitle = ""

# Activate to show authors on pages if available
#listAuthor = true

# Add math typesetting with KaTeX (Global with this Param)
math = true

# Optional 80x80 avatar image.
avatar = "/img/vitae.jpg"

# Optional favicons for website
favicon = true

# Add list of sections that should show up on the homepage
mainSections = ["post"]

# Add list of Sections/Types that should no be considered by RSS
#nofeedSections = ["post"]

# Deactivate Taxonomies for specific page types
#disableTaxoTypes = [""]

# Custom CSS applied to default styles. (Path could be "static/css/")
#customCSS = "css/custom.css"

# Navigation
[[menu.main]]
name = "English"
url = "/en"
weight = 1

[[menu.main]]
name = "Deutsch"
url = "/de"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Topics"
url = "/topics"
weight = 4

[[menu.main]]
name = "Impressum"
url = "/impressum"
weight = 5

# Social Menu
#[[params.social]]
#name = "Github"
#icon = "fab fa-github"
#url = "https://github.com/dataCobra/hugo-vitae"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
